name: Node.js Setup and Hello

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Log message
      run: echo "Hello from @siddhishetkar"
